services:
  postgres-keycloak:
    image: postgres:17
    container_name: postgres-keycloak
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql
    ports:
      - '3998:5432' # Mapped to 3998 to prevent conflicts
    networks:
      - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.6
    container_name: keycloak
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 1234
    command:
      - start-dev
    ports:
      - '9090:8080' # Keycloak running on 9090
    depends_on:
      - postgres-keycloak
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - keycloak-net

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin-server
    restart: unless-stopped
    ports:
      - '9411:9411'
    networks:
      - keycloak-net
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - keycloak-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - keycloak-net

volumes:
  postgres-keycloak-data:
  keycloak-data:
  zookeeper-data:
  kafka-data:

networks:
  keycloak-net:
  