server:
  port: 8080

spring:
  application:
    name: user-server
    
  datasource:
    url: jdbc:postgresql://localhost:3998/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/user

keycloak:
  server-url: http://localhost:9090
  realm: user
  admin:
    realm: master
    client-id: admin-cli
    username: admin
    password: admin